### PR TITLE
Use a keymap

### PR DESCRIPTION
**Pull request by Silex**
This change is pretty obvious, but it also raises questions about the other bindings that don't start with `gr` and consistency.

I feel that binding `C-n` `C-p` etc is kinda invasive... those could also be on the `gr` prefix, e.g `g r C-n` etc.

### CODE REVIEW

**Comment by Silex** [comment]
Rebased.

**Comment by duianto** [comment]
This change broke `evil-mc`:
error: (wrong-type-argument listp evil-mc-make-all-cursors) on load #106

**Comment by Silex** [comment]
Oops, sorry :sweat:

**Comment by duianto** [comment]
It happens.

Investigate how the error occurred, maybe you had some local configurations that hid the startup warning. Or it might not have been tested thoroughly.

Try to find what the issue was, fix it and resubmit a working PR.

Just learn from it and keep moving forward. 😄

**Pull request merged**
